apiVersion: v1
kind: Template
metadata:
  name: event-brite-secret
  annotations:
    description: "The Eventbrite api key secret template"
objects:
- data:
    EVENT_BRITE_API_KEY: ${EVENT_BRITE_API_KEY}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: devhub-eventbrite-secret
parameters:
- description: The CSI Lab event brite access token
  displayName: Eventbrite-key
  name: EVENT_BRITE_API_KEY
  required: true
